name: itracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localization: ^0.2.0
  get_it: ^7.6.7
  responsive_sizer: ^3.3.0+1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  syncfusion_flutter_charts: ^25.1.41+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.16.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

